version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - backend
    networks:
      - mynetwork

  backend:    
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - db
    restart: always
    networks:
      - mynetwork
    

  db:
    container_name: db
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: final_project_db
      MYSQL_ROOT_PASSWORD: user
      
    volumes:
      - ./db/final_project_db.sql:/docker-entrypoint-initdb.d/final_project_db.sql
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge